language: android
sudo: false
android:
  components:
    - tools
    - build-tools-23.0.2
    - build-tools-22.0.1
    - android-23
    - android-22
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - '.*intel.+'
before_install:
  - chmod +x gradlew
  - git submodule update --init --recursive
install:
  - ./gradlew
script:
  - ./gradlew assembleRelease --stacktrace
