language: android
sudo: false
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-27.0.2
    - android-27
  licenses:
    - 'android-sdk-license-.+'
    - '.*intel.+'
before_install:
  - chmod +x gradlew
  - git submodule update --init --recursive
install:
  - ./gradlew
script:
  - ./gradlew :app:assembleDebug --stacktrace
  - ./gradlew :app:test --stacktrace
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
